### ISSUE TITLE
Security vulnerability!!!

### ISSUE THREAD

**Issue by derekchai** [SquirtleSquadProgramming/poker_server#1]
@s-0fia

**Comment by s-0fia** [comment]
If you actually knew anything about this code base, you'd know that we are running the server on an Ubuntu, and if you read the "security" vulnerability, you'd know that it only applies to windows systems.

Therefore, this is _**irrelevant**_.

**Comment by derekchai** [comment]
Hi Elle,

I have spoken with HR regarding your passive-aggressive tone.

Here at SSP we strive to maintain an inclusive and respectful workplace
environment. I believe your behaviour does not belong in our team.

I would like this to serve as a warning for you, and I would like you to
understand that behaviour like yours will not be tolerated.

Kind regards,

Derek
